version: '3'
services:
  backend:
    build:
      context: .
      args:
        NODE_ENV: development
    env_file:
      - ./.env
    command: npm run dev
    volumes:
      - ./:/app
      - /app/node_modules
  #service-2
  frontend:
    build:
      context: ./client

  #service-3
  nginx:
    ports:
      - "5000:80"
  #service-4
  redis:
    image: redis
