version: '3'
services:
  backend:
    build: 
      context: .
      args:
        NODE_ENV: production
    command: npm run build 
  #service-2
  frontend:
    build:
      context: ./client
    command: npm run build   
  #service-3  
  nginx:
    image: nginx
    ports:
      - "80:80"
  #service-4
  redis:
    image: redis     
