version: '3'
services:
  #service-1 
  backend:
    build: .
  #service-2    
  frontend:
    build:
      context: ./client
  #service-3  
  nginx:
    image: nginx
    build: 
      context: ./nginx
    ports:
      - "5000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #service-4
  redis:
    image: redis
    build: .
